version: '3'

services:
  app:
    build:
      args:
        user: ${USER_NAME}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lms_web:latest
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_SOURCE}:/var/www/
      # - ./logs/app/:/var/www/storage/logs/
    networks:
      local:
        ipv4_address: ${APP_IPV4}


  nginx:
    image: nginx:1.21
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${LOCAL_PORT}:80
    volumes:
      - ${APP_SOURCE}:/var/www
      - ./nginx:/etc/nginx/conf.d/
      # - ./logs/nginx/:/var/log/nginx/
    networks:
     local:
      ipv4_address: ${NGINX_IPV4}

networks:
  local:
    driver: bridge
    external: true
